### ISSUE TITLE
CSDN文章不会自动居中

### ISSUE THREAD

**Issue by AdeCaspeer** [wandou-cc/blog-ui#4]
![image](https://user-images.githubusercontent.com/69611251/225497937-51886eea-bcd8-4652-9c85-92af359bd1de.png)
## 只有点击设置里的作者信息，开启后关闭 文章部分才会变长居中
![image](https://user-images.githubusercontent.com/69611251/225498108-76e809dd-7578-4c46-8868-793e7033eb39.png)

**Comment by wandou-cc** [comment]
好的 已经定位到问题
