### ISSUE TITLE
知乎无法触屏滚动

### ISSUE THREAD

**Issue by zhufengning** [wandou-cc/blog-ui#6]
系统：Win10
浏览器：edge, tampermonkey

**Comment by wandou-cc** [comment]
知乎目前是只加了 外链跳转没有加其他功能

**Comment by zhufengning** [comment]
> 知乎目前是只加了 外链跳转没有加其他功能

但是打开脚本就滑不动，关上就正常。
新建一个同样作用域的空脚本也是正常的，所以应该不是tampermonkey的问题。
